// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tjenamannen.Data;

#nullable disable

namespace tjenamannen.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230707003634_update")]
    partial class update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tjenamannen.Models.Ordklass", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Ordklasser");
                });

            modelBuilder.Entity("tjenamannen.Models.Player", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Deaths")
                        .HasColumnType("int");

                    b.Property<int>("Kills")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uuid");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("tjenamannen.Models.Word", b =>
                {
                    b.Property<string>("WordId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrdklassName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("WordId");

                    b.HasIndex("OrdklassName");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("tjenamannen.Models.Word", b =>
                {
                    b.HasOne("tjenamannen.Models.Ordklass", "Ordklass")
                        .WithMany()
                        .HasForeignKey("OrdklassName");

                    b.Navigation("Ordklass");
                });
#pragma warning restore 612, 618
        }
    }
}
