// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tjenamannen.Data;

#nullable disable

namespace tjenamannen.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tjenamannen.Models.Ordklass", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Ordklasser");
                });

            modelBuilder.Entity("tjenamannen.Models.Word", b =>
                {
                    b.Property<string>("WordId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrdklassName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("WordId");

                    b.HasIndex("OrdklassName");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("tjenamannen.Models.Word", b =>
                {
                    b.HasOne("tjenamannen.Models.Ordklass", "Ordklass")
                        .WithMany()
                        .HasForeignKey("OrdklassName");

                    b.Navigation("Ordklass");
                });
#pragma warning restore 612, 618
        }
    }
}
