name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x' 

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: aspnet-build
        path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build 

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: aspnet-build
        path: ./publish

    - name: Deploy to IIS Server
      env:
        IIS_USER: ${{ secrets.IIS_USER }}
        IIS_PASS: ${{ secrets.IIS_PASS }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
      run: |
        sudo apt-get install -y sshpass
        sshpass -p $IIS_PASS scp -r ./publish/* $IIS_USER@$SERVER_IP:$DEPLOY_DIR
        sshpass -p $IIS_PASS ssh $IIS_USER@$SERVER_IP "iisreset /restart"
